**Project Overview**: this project is all about claassify the flowers species('Iris-setosa' 'Iris-versicolor' 'Iris-virginica'), based on their characterstics (sepal and petal width and length), so we are going to bulid a neural network using tensorflow to classify these flowers.


## importing the required libraries


In [ ]:
import pandas as pd
import numpy as np
from tensorflow import keras

##EDA


In [ ]:
# reading the dataset and stores it into dataframe df, then presentinf the first 5 rows from the dataframe
df = pd.read_csv('/content/IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
#count the occurencies for each species class
df['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
#presenting a summary for the dataset and its fields
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
#checking for null values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Data Preprocessing

In [ ]:
#converting species column from species names to numerical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])
df.head()


sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
# print the original species names
species_name = le.classes_
print(species_name)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [ ]:
# creating new dataframe from the original one, x dataframe represents the input
# features , y represents the target variable for the classification task which
# the model will try to predict.
X = df.drop(columns=['species'])
y = df['species']
X.head(3)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [ ]:
#representing the first 5 rows of the target df that contains species coulmn
print(y[:5])

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64


##splitting data into train and test

shuffle is set to the defult value 'true' to randomize tha dataset and avoid an bias specill if it related to the order of the data, setting the random state = 69

In [ ]:
#
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=69)

In [ ]:
#showing number of rows and columns
x_train.shape

(105, 4)

In [ ]:
#standrize the data for each field  by using standardsacalaer setting the mean to 0 and standard deviation to 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
print(x_train[:1])
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train[:1])

    sepal_length  sepal_width  petal_length  petal_width
57           4.9          2.4           3.3          1.0
[[-1.14630942 -1.44374444 -0.25650655 -0.258263  ]]


In [ ]:
# applying one hot encoding for the species classes dataframe y, each column
# represent a class and each row representing the samples incase of this sample
# from the column category the value for it is set to 1 else it set to 0
y_train = keras.utils.to_categorical(y_train, num_classes=3)
print(y_train[:5])

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


##intializing sequential model, and the required layers

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(x_train.shape[-1], )))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=3, activation='softmax'))

In [ ]:
# setting the adam optimizier, loss function and accuracy then geeting the data
# summary
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 32)                160       
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1315 (5.14 KB)
Trainable params: 1315 (5.14 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#training the model, through 100 epoch getting the loss and accuracy for each epoch
new_var = model.fit(x_train, y_train, epochs=100)


Epoch 1/100
4/4 [==============================] - 0s 7ms/step - loss: 0.1460 - accuracy: 0.9333
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1182 - accuracy: 0.9619
Epoch 3/100
4/4 [==============================] - 0s 15ms/step - loss: 0.0948 - accuracy: 0.9619
Epoch 4/100
4/4 [==============================] - 0s 12ms/step - loss: 0.1137 - accuracy: 0.9619
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 0.0962 - accuracy: 0.9714
Epoch 6/100
4/4 [==============================] - 0s 10ms/step - loss: 0.1135 - accuracy: 0.9524
Epoch 7/100
4/4 [==============================] - 0s 8ms/step - loss: 0.1706 - accuracy: 0.9524
Epoch 8/100
4/4 [==============================] - 0s 12ms/step - loss: 0.0951 - accuracy: 0.9714
Epoch 9/100
4/4 [==============================] - 0s 7ms/step - loss: 0.0927 - accuracy: 0.9619
Epoch 10/100
4/4 [==============================] - 0s 7ms/step - loss: 0.0891 - accuracy: 0.9619
Epoch 11/100
4/4 [=======

In [ ]:
#giving predictions on the test data, representing the first five predctions
prediction = model.predict(x_test)
print(prediction[:5])

2/2 [==============================] - 0s 6ms/step
[[9.9959451e-01 1.1668835e-04 2.8887010e-04]
 [1.0762533e-02 8.7363827e-01 1.1559917e-01]
 [9.9750066e-01 1.2852958e-03 1.2139981e-03]
 [2.8399852e-04 6.5980270e-03 9.9311781e-01]
 [9.9652886e-01 1.7172286e-03 1.7538605e-03]]


In [ ]:
# converting the predictions into defined lables refering to classes for each
# sample, using argmax function with -1 parametr refering to classes
prediction = np.argmax(prediction, axis=-1)
print(prediction[:5])

[0 1 0 2 0]


the argmax functions working on converting these probability distributions into class labels by selecting the class with the highest probability.

In [ ]:
#presenting the sample index and the corresponding class label
print(y_test[:5])

4      0
58     1
20     0
114    2
31     0
Name: species, dtype: int64


In [ ]:

#imorting the accuracy_score function from sklearn.metrics module,
#this function take the y_test: the actual target labels and predection: the predicted labels generated by the model for the test dataset
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, prediction))

0.9777777777777777


This model gives 97% accuracy.